config/routes.rb
BasicCamp::Application.routes.draw do

  get "projects/index"
  get "users/index"
  root to: 'welcome#index'
  resources :projects do
    resources :todos
    resources :discussions
    resources :assets
  end
  resources :discussions, only: [:index] do
    resources :messages
  end

  namespace :admin do
    resources :users, only: [:index] 
    resources :projects, only: [:index]
  end

  resources :invitations, only: [:new, :create, :show] do
    resources :participants, only: [:new, :create]
  end

  resource :profile, only: [:edit, :update]
  resources :users, only: [:new, :create]
  resource :subscription, only: [:new, :create]
  resources :sessions, only: [:index, :create, :destroy], path: :login
  

  

end

app/models/asset.rb
class Asset < ActiveRecord::Base
  belongs_to :project
  belongs_to :user
  mount_uploader :file, FileUploader
end

app/models/discussion.rb
class Discussion < ActiveRecord::Base
  belongs_to :project
  belongs_to :user
  has_many :messages
  scope :order_by_date, lambda { order('created_at DESC') }

  validates :subject, :content, presence: true
end

app/models/invitation.rb
class Invitation < ActiveRecord::Base
  default_value_for :token do
    loop do
      random_token = SecureRandom.hex
      break random_token unless Invitation.exists?(token: random_token)
    end
  end

  belongs_to :project
  belongs_to :inviter, class_name: :User

  validates :email, presence: true, uniqueness: { scope: :project_id }
  validates :project, presence: true
  validates :token, presence: true
  validates :inviter, presence: true

  after_create :send_email

  protected
  def send_email
    UserMailer.invitation_to_project_email(self).deliver
  end
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :Discussion
  belongs_to :User

  validates :subject, presence: true
  validates :content, presence: true
  
  scope :order_by_date, lambda { order('created_at DESC') }
end

app/models/participant.rb
class Participant < ActiveRecord::Base
  # Associations
  belongs_to :user
  belongs_to :project

  # Validations
  validates :user, presence: true, uniqueness: { scope: :project_id }
  validates :project, presence: true
end

app/models/payment.rb
class Payment < ActiveRecord::Base
  belongs_to :subscription
  validates :subscription, presence: true
  validates :amount, presence: true, numericality: true
  validates :paid_at, presence: true
end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :users, through: :participants
  has_many :participants, dependent: :destroy
  has_many :todos
  has_many :discussions
  has_many :assets
  has_many :invitations

  belongs_to :owner, class_name: "User"

  validates :name, :description, presence: true

  after_create :add_owner_as_participant

  protected

  def add_owner_as_participant
    @participant = Participant.create(project_id: self.id, user_id: self.owner_id)
  end
end

app/models/subscription.rb
class Subscription < ActiveRecord::Base

  # Associations
  belongs_to :user
  has_many :payments

  # Callback
  before_create :start_subscription

  # Default values
  default_value_for :start_date do
    Date.today
  end

  default_value_for :next_payment_date do
    Date.today.advance(months: 1)
  end

  # Scope
  scope :requires_rebill, -> { Subscription.where("last_payment_date <= ?", Date.today.advance(months: -1)) }
  
  # Validations
  validates :user, presence: true
  validates :start_date, presence: true

  protected

  def start_subscription
    p = SubscriptionCharge.new(self).charge!
    unless p
      errors.add :base, "Failed payment"
      return false
    end
  end
end

app/models/subscription_charge.rb
class SubscriptionCharge

  PLAN_AMOUNT = 800

  def initialize(sub)
    @subscription = sub
  end

  Stripe.api_key = "sk_test_3ZATQU9gTIrSVcbGre3Ce6ZH"

  def charge!
    begin
      result = Stripe::Charge.create(
                 amount: PLAN_AMOUNT,
                 currency: "cad",
                 customer: @subscription.user.customer_token
               )
      @subscription.last_payment_date = Date.today
      @subscription.next_payment_date = @subscription.next_payment_date.advance(months: 1)
      payment = @subscription.payments.create(amount: PLAN_AMOUNT, paid_at: Time.now)
    rescue Stripe::CardError => e
      # TODO: SEND FAILURE EMAIL
      nil
    end
  end
end

app/models/todo.rb
class Todo < ActiveRecord::Base
  belongs_to :project

  scope :sort_by, lambda { order('due_date ASC')}

  validates :name, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :projects, through: :participants
  has_many :participants
  has_many :discussions
  has_many :messages
  has_one :subscription

  mount_uploader :avatar, AvatarUploader
  has_secure_password

  validates :username, uniqueness: { case_sensitive: false }, presence: true
  validates :email, uniqueness: { case_sensitive: false }, presence: true, email: true
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :password, length: { in: 6..20 }, on: :create
  validates :noc, presence: true, if: "paid"
  validates :cc_token, presence: true, if: "paid"
  validates :cc_type, presence: true, if: "paid"
  validates :exp, presence: true, if: "paid"
  validates :street, presence: true, if: "paid"
  validates :province, presence: true, if: "paid"
  validates :postal, presence: true, if: "paid"
  validates :country, presence: true, if: "paid"

  def full_name
    "#{first_name} #{last_name}".strip
  end

end

app/controllers/discussions_controller.rb
class DiscussionsController < ApplicationController

  before_action :restrict_access, :require_user, :require_project
  before_action :require_discussion, only: [:edit, :update, :show]

  def show
    @messages = @discussion.messages.order_by_date
    @message = @discussion.messages.new
  end

  def update
    if @discussion.update_attributes(discussion_params)
      redirect_to project_discussions_path, notice: "Discussion was created successfully."
    else
      render :edit
    end
  end

  def index
    @discussions = @project.discussions.order_by_date
  end

  def edit
  end

  def new
    @discussion = @project.discussions.new
  end

  def create
    @discussion = @project.discussions.new(discussion_params)
    @discussion.user_id = current_user.id
    if @discussion.save
      redirect_to project_discussions_path, notice: "Discussion was created successfully."
    else
      render :new
    end
  end

  protected

  def require_discussion
    @discussion = @project.discussions.find(params[:id])
  end

  def require_project
    @project = @user.projects.find(params[:project_id])
  end

  def require_user
    @user = current_user
  end

  def discussion_params
    params.require(:discussion).permit(:subject, :content)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_alert(key)
    if key == :notice
      key = :success
    elsif key == :alert
      key = :danger
    else
      key
    end
  end
end

app/helpers/assets_helper.rb
module AssetsHelper

  def file_name(asset)
    if asset.file.url
      name = asset.file.url.split('/').last
      name.length > 10 ? name[0..10] + '..' : name
    end
  end

  def user_image_thumb_url(user)
    if @user.avatar.blank?
      "/assets/default_photo_thumb.jpg"
    else
      @user.avatar.url(:small_thumb)
    end
  end

  def user_image_url(user)
    if @user.avatar.blank?
      "/assets/default_photo.jpg"
    else
      @user.avatar.url(:thumb)
    end
  end
end

app/helpers/discussions_helper.rb
module DiscussionsHelper
  def author_name(message)
    user = User.find(message.user_id)
    user.full_name
  end
  def pretty_date(date)
    date.strftime("%b %d, %Y")
  end
  def short_date(date)
    date.strftime("%b %d")
  end
end

app/helpers/invitations_helper.rb
module InvitationsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
  def trim_description(description)
    if description.length > 120
      description[0..120] + "..."
    else
      description
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/todos_helper.rb
module TodosHelper
  def completed(condition)
    return condition ? "Yes" : "No"
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/discussions/_add_message.html.erb
<div class="row add-comment">

  <%= simple_form_for @message, url: discussion_messages_path(@discussion), method: :post, defaults: { error: false, required: false, label: false, input_html: { class: "form-control counted" } } do |f| %>
    <%= f.input :subject, placeholder: "Subject *" %>
    <%= f.input :content, input_html: { rows: 4 }, placeholder: "Type in your message *" %>
    <% if @message && @message.errors.any? %>
      <div class="alert alert-danger">
        <% @message.errors.full_messages.each_with_index do |msg, index| %>
          <p><%= index+1 %>. <%= msg %>.<p> 
        <% end %>
      </div>
      <br>
    <% end %>
    <%= f.button :submit, "Submit New Message", class: "btn btn-info" %>
  <% end %>

</div>

app/views/discussions/_discussion.html.erb
<div class="container discussion">
  <div class="row">
    <div class="well">
      <div class="row">
        <div class="col-xs-2">
          <%= image_tag user_image_thumb_url(User.find(discussion.user_id)) %>
        </div>
        <div class="col-xs-10">
          <p class="subject"><%= discussion.subject %></p>
          <p class="author">By: <%= author_name(discussion) %> on <%= pretty_date(discussion.created_at) %></p>
          <p><%= discussion.content %></p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/discussions/_messages.html.erb
<div class="container messages">
  <div class="row">
    <div class="panel panel-default panel-primary widget">
      <div class="panel-heading">
        <span class="glyphicon glyphicon-comment"></span>
        <h3 class="panel-title">Recent Messages</h3>
      </div>
      <div class="panel-body">
        <% if @messages.count > 0 %>
          <ul class="list-group">
            <% @messages.each do |message| %>
              <% unless message.id.nil? %>
                <li class="list-group-item">
                  <div class="row">
                    <div class="col-xs-2">
                      <%= image_tag user_image_thumb_url(User.find(message.user_id)) %>
                    </div>
                    <div class="col-xs-10">
                      <p class="subject"><%= message.subject %></p>
                      <p class="author">By: <%= author_name(message) %> on <%= pretty_date(message.created_at) %></p>
                        <%= link_to discussion_message_path(@discussion, message), method: :delete, confirm: "Are you sure?" do %>
                          <span class="glyphicon glyphicon-trash"></span>
                        <% end %>
                      <p><%= message.content %></p>
                    </div>
                  </div>
                </li>
              <% end %>
            <% end %>
          </ul>
        <% end %>
        <%= render '/discussions/add_message' %>
      </div>
    </div>
  </div>
</div>

app/views/discussions/edit.html.erb
<%= link_to "Back to Discussion page", project_discussions_path(@project) %>

<div class="panel panel-primary login">
  <div class="panel-heading">
    <h4>Edit Discussion</h4>
  </div>
  <br>
  <div class="panel-body">
  <%= simple_form_for @discussion, url: project_discussion_path(@project, @discussion), html: { class: "form-inline todo", role: "form" }, defaults: { required: false, error: false, input_html: {class: "form-control"} } do |f| %>
    <%= f.input :subject, label: "Subject *", input_html: { value: @discussion.subject } %>
    <%= f.input :content, label: "Content *", as: :text, input_html: { rows: 6, value: @discussion.content } %>
    <br>
    <% if @discussion && @discussion.errors.any? %>
      <div class="alert alert-danger">
        <% @discussion.errors.full_messages.each_with_index do |msg, index| %>
          <p><%= index+1 %>. <%= msg %>.<p> 
        <% end %>
      </div>
      <br>
    <% end %>
    <%= f.button :submit, "Submit your changes", class: 'btn btn-primary' %>
  <% end %>
  </div><br>
</div>

app/views/discussions/index.html.erb
<% content_for :discussions, "active" %>

<div class="container row">

  <div class="side-menu col-xs-3">
    <%= render "/layouts/side_menu" %>
  </div>
  <div class="discussion content col-xs-9">
    <%= link_to "Add a new discussion", new_project_discussion_path(@project) %>
    <div class="table-responsive">
      <table class="table table-hover">
        <thead>
          <tr>
            <th></th>
            <th>Started By</th>
            <th>Subject</th>
            <th>Discussion</th>
            <th>Date</th>
          </tr>
        </thead>
        <tbody>
          <% if @discussions %>
            <% @discussions.each do |discussion| %>
              <tr>
                <td>
                  <%= link_to project_discussion_path(@project, discussion), method: :delete, class: "delete-btn", confirm: "Are you sure?" do %>
                    <span class="glyphicon glyphicon-trash"></span>
                  <% end %>
                </td>
                <td><%= author_name(discussion) %></td>
                <td><%= link_to discussion.subject, project_discussion_path(@project, discussion.id) %></td>
                <td><%= link_to discussion.content, project_discussion_path(@project, discussion.id)%></td>
                <td><%= short_date(discussion.created_at) %></td>
              </tr>
            <% end %>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/discussions/new.html.erb
<%= link_to "Back to Discussion page", project_discussions_path(@project) %>

<div class="panel panel-primary login">
  <div class="panel-heading">
    <h4>Add a New Discussion</h4>
  </div>
  <br>
  <div class="panel-body">
  <%= simple_form_for @discussion, url: project_discussions_path, html: { class: "form-inline todo", role: "form" }, defaults: { required: false, error: false, input_html: {class: "form-control"} } do |f| %>
    <%= f.input :subject, label: "Subject *" %>
    <%= f.input :content, label: "Content *", as: :text, input_html: { rows: 6 } %>
    <br>
    <% if @discussion && @discussion.errors.any? %>
      <div class="alert alert-danger">
        <% @discussion.errors.full_messages.each_with_index do |msg, index| %>
          <p><%= index+1 %>. <%= msg %>.<p> 
        <% end %>
      </div>
      <br>
    <% end %>
    <%= f.button :submit, "Create Discussion", class: 'btn btn-primary' %>
  <% end %>
  </div><br>
</div>

app/views/discussions/show.html.erb
<% content_for :discussions, "active" %>

<div class="container row">

  <div class="side-menu col-xs-3">
    <%= render "/layouts/side_menu" %>
  </div>
  <div class="content col-xs-9">

    <%= render '/discussions/discussion', discussion: @discussion %>
    <%= render '/discussions/messages' %>

  </div>
</div>
<%= link_to "Edit this discussion", edit_project_discussion_path(@project, @discussion.id) %>