config/routes.rb
BasicCamp::Application.routes.draw do

  get "projects/index"
  get "users/index"
  root to: 'welcome#index'
  resources :projects do
    resources :todos
    resources :discussions
    resources :assets
  end
  resources :discussions, only: [:index] do
    resources :messages
  end

  namespace :admin do
    resources :users, only: [:index] 
    resources :projects, only: [:index]
  end

  resources :invitations, only: [:new, :create, :show] do
    resources :participants, only: [:new, :create]
  end

  resource :profile, only: [:edit, :update]
  resources :users, only: [:new, :create]
  resource :subscription, only: [:new, :create]
  resources :sessions, only: [:index, :create, :destroy], path: :login
  

  

end

app/models/asset.rb
class Asset < ActiveRecord::Base
  belongs_to :project
  belongs_to :user
  mount_uploader :file, FileUploader
end

app/models/discussion.rb
class Discussion < ActiveRecord::Base
  belongs_to :project
  belongs_to :user
  has_many :messages
  scope :order_by_date, lambda { order('created_at DESC') }

  validates :subject, :content, presence: true
end

app/models/invitation.rb
class Invitation < ActiveRecord::Base
  default_value_for :token do
    loop do
      random_token = SecureRandom.hex
      break random_token unless Invitation.exists?(token: random_token)
    end
  end

  belongs_to :project
  belongs_to :inviter, class_name: :User

  validates :email, presence: true, uniqueness: { scope: :project_id }
  validates :project, presence: true
  validates :token, presence: true
  validates :inviter, presence: true

  after_create :send_email

  protected
  def send_email
    UserMailer.invitation_to_project_email(self).deliver
  end
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :Discussion
  belongs_to :User

  validates :subject, presence: true
  validates :content, presence: true
  
  scope :order_by_date, lambda { order('created_at DESC') }
end

app/models/participant.rb
class Participant < ActiveRecord::Base
  # Associations
  belongs_to :user
  belongs_to :project

  # Validations
  validates :user, presence: true, uniqueness: { scope: :project_id }
  validates :project, presence: true
end

app/models/payment.rb
class Payment < ActiveRecord::Base
  belongs_to :subscription
  validates :subscription, presence: true
  validates :amount, presence: true, numericality: true
  validates :paid_at, presence: true
end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :users, through: :participants
  has_many :participants, dependent: :destroy
  has_many :todos
  has_many :discussions
  has_many :assets
  has_many :invitations

  belongs_to :owner, class_name: "User"

  validates :name, :description, presence: true

  after_create :add_owner_as_participant

  protected

  def add_owner_as_participant
    @participant = Participant.create(project_id: self.id, user_id: self.owner_id)
  end
end

app/models/subscription.rb
class Subscription < ActiveRecord::Base

  # Associations
  belongs_to :user
  has_many :payments

  # Callback
  before_create :start_subscription

  # Default values
  default_value_for :start_date do
    Date.today
  end

  default_value_for :next_payment_date do
    Date.today.advance(months: 1)
  end

  # Scope
  scope :requires_rebill, -> { Subscription.where("last_payment_date <= ?", Date.today.advance(months: -1)) }
  
  # Validations
  validates :user, presence: true
  validates :start_date, presence: true

  protected

  def start_subscription
    p = SubscriptionCharge.new(self).charge!
    unless p
      errors.add :base, "Failed payment"
      return false
    end
  end
end

app/models/subscription_charge.rb
class SubscriptionCharge

  PLAN_AMOUNT = 800

  def initialize(sub)
    @subscription = sub
  end

  Stripe.api_key = "sk_test_3ZATQU9gTIrSVcbGre3Ce6ZH"

  def charge!
    begin
      result = Stripe::Charge.create(
                 amount: PLAN_AMOUNT,
                 currency: "cad",
                 customer: @subscription.user.customer_token
               )
      @subscription.last_payment_date = Date.today
      @subscription.next_payment_date = @subscription.next_payment_date.advance(months: 1)
      payment = @subscription.payments.create(amount: PLAN_AMOUNT, paid_at: Time.now)
    rescue Stripe::CardError => e
      # TODO: SEND FAILURE EMAIL
      nil
    end
  end
end

app/models/todo.rb
class Todo < ActiveRecord::Base
  belongs_to :project

  scope :sort_by, lambda { order('due_date ASC')}

  validates :name, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :projects, through: :participants
  has_many :participants
  has_many :discussions
  has_many :messages
  has_one :subscription

  mount_uploader :avatar, AvatarUploader
  has_secure_password

  validates :username, uniqueness: { case_sensitive: false }, presence: true
  validates :email, uniqueness: { case_sensitive: false }, presence: true, email: true
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :password, length: { in: 6..20 }, on: :create
  validates :noc, presence: true, if: "paid"
  validates :cc_token, presence: true, if: "paid"
  validates :cc_type, presence: true, if: "paid"
  validates :exp, presence: true, if: "paid"
  validates :street, presence: true, if: "paid"
  validates :province, presence: true, if: "paid"
  validates :postal, presence: true, if: "paid"
  validates :country, presence: true, if: "paid"

  def full_name
    "#{first_name} #{last_name}".strip
  end

end

app/controllers/admin/projects_controller.rb
class Admin::ProjectsController < ApplicationController

  layout "admin"

  before_action :restrict_access, :restrict_admin_access
  def index
    @projects = Project.all
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  before_action :restrict_access, :require_user
  before_action :require_project, only: [:show, :edit, :update, :destroy]
  
  def show
    @discussions = @project.discussions.order_by_date.limit(3)
    @todos = @project.todos.sort_by.limit(3)
    @assets = @project.assets.limit(3)
  end

  def index
    @projects = @user.projects
  end

  def edit
  end

  def new
    @project = Project.new
  end

  def destroy
    @project.destroy
    redirect_to projects_path, notice: "Project was deleted successfully."
  end

  def create
    @project = Project.new(project_params)
    @project.owner = current_user

    if @project.save
      redirect_to projects_path, notice: "Project was created successfully."
    else
      render :new
    end
  end

  def update
    if @project.update_attributes(project_params)
      redirect_to project_path(@project), notice: "Project was updated successfully."
    else
      render :edit
    end
  end

  protected

  def require_user 
    @user = current_user
  end

  def require_project
    @project = @user.projects.find(params[:id])
  end

  def project_params
    params.require(:project).permit(:name, :description)
  end
end

app/helpers/admin/projects_helper.rb
module Admin::ProjectsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_alert(key)
    if key == :notice
      key = :success
    elsif key == :alert
      key = :danger
    else
      key
    end
  end
end

app/helpers/assets_helper.rb
module AssetsHelper

  def file_name(asset)
    if asset.file.url
      name = asset.file.url.split('/').last
      name.length > 10 ? name[0..10] + '..' : name
    end
  end

  def user_image_thumb_url(user)
    if @user.avatar.blank?
      "/assets/default_photo_thumb.jpg"
    else
      @user.avatar.url(:small_thumb)
    end
  end

  def user_image_url(user)
    if @user.avatar.blank?
      "/assets/default_photo.jpg"
    else
      @user.avatar.url(:thumb)
    end
  end
end

app/helpers/discussions_helper.rb
module DiscussionsHelper
  def author_name(message)
    user = User.find(message.user_id)
    user.full_name
  end
  def pretty_date(date)
    date.strftime("%b %d, %Y")
  end
  def short_date(date)
    date.strftime("%b %d")
  end
end

app/helpers/invitations_helper.rb
module InvitationsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
  def trim_description(description)
    if description.length > 120
      description[0..120] + "..."
    else
      description
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/todos_helper.rb
module TodosHelper
  def completed(condition)
    return condition ? "Yes" : "No"
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/projects/index.html.erb
<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>Project Name</th>
      <th>Project Owner</th>
    </tr>
  </thead>
  <tbody>
    <% unless @projects.empty? %>
      <% @projects.each do |project| %>
        <tr>
          <td><%= project.name %></td>
          <td><%= project.owner.first_name %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

app/views/projects/edit.html.erb
<%= link_to "Back to all projects", projects_path %>

<div class="panel panel-primary login">
  <div class="panel-heading">
    <h4>Edit Project</h4>
  </div>
  <br>
  <div class="panel-body">
  <%= simple_form_for @project, html: { class: "form-inline", role: "form" }, defaults: { required: false, error: false, input_html: {class: "form-control"} } do |f| %>
    <%= f.input :name, label: "Name *", input_html: { value: @project.name } %>
    <%= f.input :description, label: "Description *", as: :text, input_html: { rows: 6, value: @project.description } %>
    <br>
    <% if @project && @project.errors.any? %>
      <div class="alert alert-danger">
        <% @project.errors.full_messages.each_with_index do |msg, index| %>
          <p><%= index+1 %>. <%= msg %>.<p> 
        <% end %>
      </div>
      <br>
    <% end %>
    <%= f.button :submit, "Submit your changes", class: 'btn btn-primary' %>
  <% end %>
  </div><br>
</div>

app/views/projects/index.html.erb
<div class="home container">
  <div class="projects row">
    <% if @projects %>
      <% @projects.each do |project| %>  
        <div class="col-xs-6 col-sm-6 col-md-3 col-lg-3">
          <div class="thumbnail">
            <p class="title">
              <%= project.name %>
              <%= link_to project_path(project), method: :delete, data: { confirm: "Are you sure?" } do %>
                <span class="glyphicon glyphicon-trash"></span>
              <% end %>
            </p>
            <%= link_to project_path(project) do %>
              <%= image_tag "project.png" %>
            <% end %>
            <p class="description">
              <%= trim_description(project.description) %>
            </p>
            <p class="view-btn"><%= link_to "View", project_path(project), class: "btn btn-primary btn-lg btn-block" %></p>
          </div>
        </div>
      <% end %>
    <% end %>
    <div class="col-xs-6 col-sm-6 col-md-3 col-lg-3">
      <div class="thumbnail">
      <p class="title">&nbsp;</p>
        <%= link_to new_project_path do %>
          <%= image_tag "add_new_project.png", class: "add" %>
        <% end %>
        <p class="description"></p>
        <p class="view-btn"><%= link_to "Add New", new_project_path, class: "btn btn-primary btn-lg btn-block" %></p>
      </div>
    </div>
  </div>
</div>

app/views/projects/new.html.erb
<div class="panel panel-primary login">
  <div class="panel-heading">
    <h4>Add a New Project</h4>
  </div>
  <br>
  <div class="panel-body">
  <%= simple_form_for @project, html: { class: "form-inline", role: "form" }, defaults: { required: false, error: false, input_html: {class: "form-control"} } do |f| %>
    <%= f.input :name, label: "Name *" %>
    <%= f.input :description, label: "Description *", as: :text, input_html: { rows: 6 } %>
    <br>
    <% if @project && @project.errors.any? %>
      <div class="alert alert-danger">
        <% @project.errors.full_messages.each_with_index do |msg, index| %>
          <p><%= index+1 %>. <%= msg %>.<p> 
        <% end %>
      </div>
      <br>
    <% end %>
    <%= f.button :submit, "Create Project", class: 'btn btn-primary' %>
  <% end %>
  </div><br>
</div>

app/views/projects/show.html.erb
<% content_for :home, "active" %>
<div class="container row">

  <div class="side-menu col-xs-3">
    <%= render "/layouts/side_menu" %>
  </div>
  <div class="content col-xs-9">
    <div class="row jumbotron">
      <h1><%= @project.name %></h1>
      <p><%= @project.description %></p>
    </div>
    <%= link_to "Add User", '#' %>
    <!-- Todo -->
    <div class="row project-todo">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title">Todos</h3>
          <%= link_to "More", project_todos_path(@project) %>
        </div>
        <div class="panel-body">
          <div class="table-responsive">
            <table class="table table-hover">
              <thead>
                <tr>
                  <th>Name</th>
                  <th>Importance</th>          
                  <th>Due Date</th>
                  <th>Completed</th>
                </tr>
              </thead>  
              <tbody>
                <% if @todos %>
                  <% @todos.each do |todo| %>
                    <tr>
                      <td><%= todo.name %></td>
                      <td><%= todo.importance %></td>
                      <td><%= todo.due_date %></td>
                      <td><%= completed(todo.completed) %></td>
                    </tr>
                  <% end %>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>

    <!-- Discussion -->
    <div class="row project-discussion">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title">Discussions</h3>
          <%= link_to "More", project_discussions_path(@project) %>
        </div>

        <div class="panel-body">
          <div class="table-responsive">
            <table class="table table-hover">
              <thead>
                <tr>
                  <th>Started By</th>
                  <th>Subject</th>
                  <th>Discussion</th>
                  <th>Date</th>
                </tr>
              </thead>
              <tbody>
                <% if @discussions %>
                  <% @discussions.each do |discussion| %>
                    <tr>
                      <td><%= author_name(discussion) %></td>
                      <td><%= link_to discussion.subject, project_discussion_path(@project, discussion.id) %></td>
                      <td><%= link_to discussion.content, project_discussion_path(@project, discussion.id)%></td>
                      <td><%= short_date(discussion.created_at) %></td>
                    </tr>
                  <% end %>
                <% end %>
              </tbody>
            </table>
          </div>   
        </div>
      </div>   
    </div>

    <!-- Files -->
    <div class="row project-file">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title">Files</h3>
          <%= link_to "More", project_assets_path(@project) %>
        </div>
        <div class="panel-body">
          <% if @assets %>
            <% @assets.each do |asset| %>  
              <% unless asset.id.nil? %>
                <div class="col-xs-6 col-sm-6 col-md-3 col-lg-3">
                  <div class="thumbnail">
                    <%= image_tag "file.png" %>
                    <p class="title">
                      <%= file_name(asset) %>
                    </p>
                  </div>
                </div>
              <% end %>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>

  </div>
</div>

<br>
<%= link_to "Edit this project", [:edit, @project] %>