config/routes.rb
BasicCamp::Application.routes.draw do

  get "projects/index"
  get "users/index"
  root to: 'welcome#index'
  resources :projects do
    resources :todos
    resources :discussions
    resources :assets
  end
  resources :discussions, only: [:index] do
    resources :messages
  end

  namespace :admin do
    resources :users, only: [:index] 
    resources :projects, only: [:index]
  end

  resources :invitations, only: [:new, :create, :show] do
    resources :participants, only: [:new, :create]
  end

  resource :profile, only: [:edit, :update]
  resources :users, only: [:new, :create]
  resource :subscription, only: [:new, :create]
  resources :sessions, only: [:index, :create, :destroy], path: :login
  

  

end

app/models/asset.rb
class Asset < ActiveRecord::Base
  belongs_to :project
  belongs_to :user
  mount_uploader :file, FileUploader
end

app/models/discussion.rb
class Discussion < ActiveRecord::Base
  belongs_to :project
  belongs_to :user
  has_many :messages
  scope :order_by_date, lambda { order('created_at DESC') }

  validates :subject, :content, presence: true
end

app/models/invitation.rb
class Invitation < ActiveRecord::Base
  default_value_for :token do
    loop do
      random_token = SecureRandom.hex
      break random_token unless Invitation.exists?(token: random_token)
    end
  end

  belongs_to :project
  belongs_to :inviter, class_name: :User

  validates :email, presence: true, uniqueness: { scope: :project_id }
  validates :project, presence: true
  validates :token, presence: true
  validates :inviter, presence: true

  after_create :send_email

  protected
  def send_email
    UserMailer.invitation_to_project_email(self).deliver
  end
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :Discussion
  belongs_to :User

  validates :subject, presence: true
  validates :content, presence: true
  
  scope :order_by_date, lambda { order('created_at DESC') }
end

app/models/participant.rb
class Participant < ActiveRecord::Base
  # Associations
  belongs_to :user
  belongs_to :project

  # Validations
  validates :user, presence: true, uniqueness: { scope: :project_id }
  validates :project, presence: true
end

app/models/payment.rb
class Payment < ActiveRecord::Base
  belongs_to :subscription
  validates :subscription, presence: true
  validates :amount, presence: true, numericality: true
  validates :paid_at, presence: true
end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :users, through: :participants
  has_many :participants, dependent: :destroy
  has_many :todos
  has_many :discussions
  has_many :assets
  has_many :invitations

  belongs_to :owner, class_name: "User"

  validates :name, :description, presence: true

  after_create :add_owner_as_participant

  protected

  def add_owner_as_participant
    @participant = Participant.create(project_id: self.id, user_id: self.owner_id)
  end
end

app/models/subscription.rb
class Subscription < ActiveRecord::Base

  # Associations
  belongs_to :user
  has_many :payments

  # Callback
  before_create :start_subscription

  # Default values
  default_value_for :start_date do
    Date.today
  end

  default_value_for :next_payment_date do
    Date.today.advance(months: 1)
  end

  # Scope
  scope :requires_rebill, -> { Subscription.where("last_payment_date <= ?", Date.today.advance(months: -1)) }
  
  # Validations
  validates :user, presence: true
  validates :start_date, presence: true

  protected

  def start_subscription
    p = SubscriptionCharge.new(self).charge!
    unless p
      errors.add :base, "Failed payment"
      return false
    end
  end
end

app/models/subscription_charge.rb
class SubscriptionCharge

  PLAN_AMOUNT = 800

  def initialize(sub)
    @subscription = sub
  end

  Stripe.api_key = "sk_test_3ZATQU9gTIrSVcbGre3Ce6ZH"

  def charge!
    begin
      result = Stripe::Charge.create(
                 amount: PLAN_AMOUNT,
                 currency: "cad",
                 customer: @subscription.user.customer_token
               )
      @subscription.last_payment_date = Date.today
      @subscription.next_payment_date = @subscription.next_payment_date.advance(months: 1)
      payment = @subscription.payments.create(amount: PLAN_AMOUNT, paid_at: Time.now)
    rescue Stripe::CardError => e
      # TODO: SEND FAILURE EMAIL
      nil
    end
  end
end

app/models/todo.rb
class Todo < ActiveRecord::Base
  belongs_to :project

  scope :sort_by, lambda { order('due_date ASC')}

  validates :name, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :projects, through: :participants
  has_many :participants
  has_many :discussions
  has_many :messages
  has_one :subscription

  mount_uploader :avatar, AvatarUploader
  has_secure_password

  validates :username, uniqueness: { case_sensitive: false }, presence: true
  validates :email, uniqueness: { case_sensitive: false }, presence: true, email: true
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :password, length: { in: 6..20 }, on: :create
  validates :noc, presence: true, if: "paid"
  validates :cc_token, presence: true, if: "paid"
  validates :cc_type, presence: true, if: "paid"
  validates :exp, presence: true, if: "paid"
  validates :street, presence: true, if: "paid"
  validates :province, presence: true, if: "paid"
  validates :postal, presence: true, if: "paid"
  validates :country, presence: true, if: "paid"

  def full_name
    "#{first_name} #{last_name}".strip
  end

end

app/controllers/assets_controller.rb
class AssetsController < ApplicationController

  before_action :require_project, :restrict_access

  def show
    @asset = @project.assets.find(params[:id])
    filename = @asset.file.url.split('/').last

    # TODO fix to upload to S3 for Heroku Deployment
    send_data @asset.file.path, filename: filename
  end

  def index
    @assets = @project.assets
    @asset = @project.assets.new
  end

  def new
    @asset = @project.assets.new
  end

  def create
    @asset = @project.assets.new(asset_params)
    @asset.user_id = current_user.id
    if @asset.save
      redirect_to project_assets_path, notice: "File was uploaded successfully."
    else
      redirect_to project_assets_path, alert: "Upload failed - invalid file format."
    end
  end

  def destroy
    @asset = @project.assets.find(params[:id])
    @asset.destroy
    redirect_to project_assets_path, notice: "File was deleted successfully."
  end

  protected

  def asset_params
    params.require(:asset).permit(:file)
  end

  def require_project
    @project = current_user.projects.find(params[:project_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_alert(key)
    if key == :notice
      key = :success
    elsif key == :alert
      key = :danger
    else
      key
    end
  end
end

app/helpers/assets_helper.rb
module AssetsHelper

  def file_name(asset)
    if asset.file.url
      name = asset.file.url.split('/').last
      name.length > 10 ? name[0..10] + '..' : name
    end
  end

  def user_image_thumb_url(user)
    if @user.avatar.blank?
      "/assets/default_photo_thumb.jpg"
    else
      @user.avatar.url(:small_thumb)
    end
  end

  def user_image_url(user)
    if @user.avatar.blank?
      "/assets/default_photo.jpg"
    else
      @user.avatar.url(:thumb)
    end
  end
end

app/helpers/discussions_helper.rb
module DiscussionsHelper
  def author_name(message)
    user = User.find(message.user_id)
    user.full_name
  end
  def pretty_date(date)
    date.strftime("%b %d, %Y")
  end
  def short_date(date)
    date.strftime("%b %d")
  end
end

app/helpers/invitations_helper.rb
module InvitationsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
  def trim_description(description)
    if description.length > 120
      description[0..120] + "..."
    else
      description
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/todos_helper.rb
module TodosHelper
  def completed(condition)
    return condition ? "Yes" : "No"
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/assets/_upload.html.erb
<%= form_for :asset, url: project_assets_path do |f| %>
  <%= f.file_field :file %>
  <%= f.submit :Upload, id: "upload" %>
<% end %>

app/views/assets/index.html.erb
<% content_for :files, "active" %>

<div class="container row">
  <div class="side-menu col-xs-3">
    <%= render "/layouts/side_menu" %>
  </div>
  <div class="content col-xs-9">
    <div class="assets">
      <div class="row">
        <% if @assets %>
          <% @assets.each do |asset| %>  
            <% unless asset.id.nil? %>
              <div class="col-xs-6 col-sm-6 col-md-3 col-lg-3">
                <div class="thumbnail">
                  <%= image_tag "file.png" %>
                  <p class="title">
                    <%= file_name(asset) %>
                    <%= link_to project_asset_path(@project, asset), method: :delete, class: "delete-btn", confirm: "Are you sure?" do %>
                      <span class="glyphicon glyphicon-trash"></span>
                    <% end %>
                  </p>
                  <p class="download-btn"><%= link_to "Download", project_asset_path(@project, asset), class: "btn btn-primary btn-lg btn-block" %></p>
                </div>
              </div>
            <% end %>
          <% end %>
        <% end %>
        <div class="col-xs-6 col-sm-6 col-md-3 col-lg-3">
          <div class="thumbnail">
            <%= link_to '#', data: { toggle: "modal", target: "#myModal" } do %>
              <%= image_tag "add_new_project.png", class: "add" %>
            <% end %>
            <p class="title">&nbsp;</p>
            <p class="upload-btn"><%= link_to "Upload New File", '#', class: "btn btn-primary btn-lg btn-block", data: { toggle: "modal", target: "#myModal" } %></p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Upload New File</h4>
      </div>
      <div class="modal-body">
        <%= render '/assets/upload', asset: @asset %>
      </div>
    </div>
  </div>
</div>

app/views/assets/new.html.erb
<%= form_for @asset, url: project_assets_path do |f| %>
  <%= f.file_field :file %>
  <%= f.submit :Upload %>
<% end %>

app/views/assets/show.html.erb
<h1>Assets#show</h1>
<p>Find me in app/views/assets/show.html.erb</p>